# Generated by Django 3.2 on 2022-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='cooking_time',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preparation_length',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='total_time',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
