# Generated by Django 3.2 on 2022-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20220317_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='serving_size',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
